(()=>{
 document.documentElement.classList.add('js');const $=s=>document.querySelector(s);let navRequest,playerTrigger;
 const frame=(src,title)=>{const f=document.createElement('iframe');f.src=src;f.title=title;f.allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture';f.allowFullscreen=true;f.referrerPolicy='strict-origin-when-cross-origin';return f;};
 const dock=document.createElement('section');dock.className='listening-dock';dock.hidden=true;dock.setAttribute('aria-label','Persistent music player');dock.innerHTML='<div class="dock-heading"><strong id="dock-title">Now listening</strong><div><button type="button" id="dock-minimize" aria-expanded="true">Minimize</button><button type="button" id="dock-close">Close player</button></div></div><div id="dock-player"></div>';document.body.append(dock);
 $('#dock-close').onclick=()=>{dock.hidden=true;$('#dock-player').replaceChildren();document.body.classList.remove('has-player');(playerTrigger?.isConnected?playerTrigger:document.querySelector('main h1'))?.focus();};$('#dock-minimize').onclick=()=>{const small=dock.classList.toggle('compact');$('#dock-player').hidden=small;$('#dock-minimize').setAttribute('aria-expanded',!small);$('#dock-minimize').textContent=small?'Expand':'Minimize';};
 function play(url,title){if(!window.BlindbanditPrivacy?.allows('media')){window.BlindbanditPrivacy?.open();return;}const u=new URL(url);if(u.hostname!=='open.spotify.com')return;playerTrigger=document.activeElement;dock.hidden=false;document.body.classList.add('has-player');$('#dock-title').textContent=title||'Mr. Blindbandit on Spotify';$('#dock-player').replaceChildren(frame('https://open.spotify.com/embed'+u.pathname+'?theme=0&utm_source=generator',title||'Spotify player'));$('#dock-title').setAttribute('tabindex','-1');$('#dock-title').focus();}
 let prefs={};try{prefs=JSON.parse(localStorage.getItem('bb-preferences')||'{}');}catch{}function preferences(){document.body.classList.toggle('motion-paused',!!prefs.paused);document.body.classList.toggle('high-contrast',!!prefs.contrast);document.body.classList.toggle('large-text',!!prefs.large);try{localStorage.setItem('bb-preferences',JSON.stringify(prefs));}catch{}const m=$('.motion-toggle');if(m){m.hidden=false;m.textContent=prefs.paused?'Resume motion':'Pause motion';m.setAttribute('aria-pressed',!!prefs.paused);}document.querySelectorAll('[data-preference]').forEach(b=>b.setAttribute('aria-pressed',!!prefs[b.dataset.preference]));}preferences();
 $('.motion-toggle')?.addEventListener('click',()=>{prefs.paused=!prefs.paused;preferences();});
 let scheduled=false;function progress(){const total=document.documentElement.scrollHeight-innerHeight;if($('.scroll-progress'))$('.scroll-progress').style.transform=`scaleX(${total>0?scrollY/total:0})`;scheduled=false;}addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(progress);}},{passive:true});
 const menu=$('.menu');const mainNav=$('nav[aria-label="Main navigation"]')||$('nav');if(mainNav){mainNav.id='main-navigation';menu?.setAttribute('aria-controls',mainNav.id);}document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu?.getAttribute('aria-expanded')==='true'){mainNav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menu +';menu.focus();}});if(menu){menu.hidden=false;menu.onclick=()=>{const o=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',o);mainNav.classList.toggle('open',o);menu.textContent=o?'Close ×':'Menu +';};}
 const dialog=$('#music-dialog');$('.close-dialog')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('close',()=>$('#dialog-player').replaceChildren());
 document.addEventListener('click',e=>{const b=e.target.closest('[data-spotify]');if(b){e.preventDefault();play(b.dataset.spotify,b.dataset.name);return;}const p=e.target.closest('[data-preference]');if(p){prefs[p.dataset.preference]=!prefs[p.dataset.preference];preferences();return;}const a=e.target.closest('a');if(!a||e.defaultPrevented||e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||a.hasAttribute('download')||a.target||a.dataset.fullNavigation!==undefined)return;if(/^\/(portal|owner)(\/|$)|^\/community\/(account|dashboard|moderation)(\/|$)/.test(new URL(a.href).pathname))return;const raw=a.getAttribute('href');if(!raw||raw.startsWith('#'))return;const u=new URL(a.href);if(u.origin!==location.origin||!['http:','https:'].includes(u.protocol)||/\.(txt|jpg|png|svg|pdf|xml)$/.test(u.pathname)||/^\/(signin-with-chatgpt|signout-with-chatgpt|callback|api)(\/|\?|$)/.test(u.pathname))return;e.preventDefault();navigate(u.pathname+u.search+u.hash);});
 async function navigate(path,push=true){navRequest?.abort();navRequest=new AbortController();try{const r=await fetch(path,{signal:navRequest.signal});if(!r.ok)throw Error('Navigation failed');const text=await r.text(),doc=new DOMParser().parseFromString(text,'text/html'),main=doc.querySelector('main');if(Boolean(document.querySelector('script[src*="adsbygoogle.js"]'))!==Boolean(doc.querySelector('script[src*="adsbygoogle.js"]'))){location.assign(path);return;}if(!main)throw Error('Page unavailable');if(document.querySelector('[data-media-tool],[data-audio-converter]')||doc.querySelector('[data-media-tool],[data-audio-converter]')){location.assign(path);return;}if(['public-modern','legal-page','localized-page','label-page'].some(c=>doc.body.classList.contains(c)!==document.body.classList.contains(c))||[...doc.scripts].some(s=>s.src&&![...document.scripts].some(t=>t.getAttribute('src')===s.getAttribute('src')))){location.assign(path);return;}$('main').replaceWith(main);document.title=doc.title;const managed='meta[name=description],meta[name=robots],meta[name^=twitter],meta[property^=og],link[rel=alternate],script[type="application/ld+json"]';document.head.querySelectorAll(managed).forEach(el=>el.remove());doc.head.querySelectorAll(managed).forEach(el=>document.head.append(el.cloneNode(true)));document.body.classList.toggle('label-page',doc.body.classList.contains('label-page'));const canonical=$('link[rel=canonical]');if(canonical)canonical.href=doc.querySelector('link[rel=canonical]')?.href||location.origin+path;document.querySelectorAll('nav a').forEach(a=>{if(new URL(a.href).pathname===new URL(path,location.origin).pathname)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(push)history.pushState({},'',path);$('nav').classList.remove('open');menu?.setAttribute('aria-expanded','false');if(menu)menu.textContent='Menu +';init();document.dispatchEvent(new Event('site:navigate'));const h=$('main h1');if(h){h.setAttribute('tabindex','-1');h.focus({preventScroll:true});}if(location.hash){document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView();}else scrollTo({top:0,behavior:'instant'});}catch(e){if(e.name!=='AbortError')location.assign(path);}}
 addEventListener('popstate',()=>navigate(location.pathname+location.search+location.hash,false));
 function init(){const copyAttribution=document.querySelector('[data-copy-attribution]');if(copyAttribution&&navigator.clipboard){copyAttribution.hidden=false;copyAttribution.onclick=async()=>{const code=document.getElementById('attribution-code'),status=document.querySelector('[data-attribution-status]');try{await navigator.clipboard.writeText(code.value);status.textContent='Official website link copied.';}catch{code.focus();code.select();status.textContent='Select and copy the website link above.';}};}preferences();progress();if('IntersectionObserver'in window){const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.section-heading,.portal-grid,.feature,.story-copy h2').forEach(el=>{el.classList.add('reveal');observer.observe(el);});}
 document.querySelectorAll('.load-player').forEach(b=>b.onclick=()=>{if(!window.BlindbanditPrivacy?.allows('media')){window.BlindbanditPrivacy?.open();return;}const p=b.closest('.player');if(p.dataset.player==='Spotify'){play('https://open.spotify.com/artist/'+p.dataset.media,'Mr. Blindbandit on Spotify');}else p.replaceChildren(frame('https://www.youtube-nocookie.com/embed/'+p.dataset.media+'?autoplay=1&rel=0','YouTube video player'));});
 document.querySelectorAll('[data-apple]').forEach(b=>b.onclick=()=>{if(!window.BlindbanditPrivacy?.allows('media')){window.BlindbanditPrivacy?.open();return;}$('#player-title').textContent=b.dataset.name;$('#dialog-player').replaceChildren(frame(b.dataset.apple.replace('music.apple.com','embed.music.apple.com'),'Apple Music: '+b.dataset.name));dialog.showModal();});
 const search=$('#search');if(search){$('.filters').hidden=false;const format=$('#format'),year=$('#year-filter'),records=[...document.querySelectorAll('.catalog .record')];const filter=()=>{let n=0;records.forEach(r=>{const v=r.dataset.title.includes(search.value.trim().toLowerCase())&&(!format.value||format.value===r.dataset.type)&&(!year.value||year.value===r.dataset.year);r.hidden=!v;if(v)n++;});$('#result-count').textContent=`${n} release${n===1?'':'s'}`;$('#empty-results').hidden=n!==0;};search.oninput=filter;format.onchange=filter;year.onchange=filter;$('#reset-filters').onclick=()=>{search.value=format.value=year.value='';filter();search.focus();};}
 for(const [id,value,status]of [['copy-email','business@mrblindbandit.net','copy-status'],['copy-paypal','@internethorror','paypal-status']]){const b=document.getElementById(id);if(b&&navigator.clipboard){b.hidden=false;b.onclick=async()=>{try{await navigator.clipboard.writeText(value);document.getElementById(status).textContent='Copied: '+value;}catch{document.getElementById(status).textContent='Please select and copy: '+value;}};}}
 const brief=$('#brief-form');if(brief){brief.onsubmit=e=>{e.preventDefault();const d=new FormData(brief),text=['Project inquiry — '+d.get('name'),'Type: '+d.get('type'),'','Project: '+d.get('idea'),'Reference: '+(d.get('reference')||'Not provided'),'Timeline: '+(d.get('timeline')||'To discuss'),'Budget: '+(d.get('budget')||'To discuss')].join('\n');$('#brief-output').value=text;const mail=$('#email-brief');mail.href='mailto:business@mrblindbandit.net?subject='+encodeURIComponent('Project inquiry: '+d.get('name'))+'&body='+encodeURIComponent(text);mail.hidden=false;const copy=$('#copy-brief');copy.hidden=false;copy.onclick=async()=>{try{await navigator.clipboard.writeText(text);$('#brief-status').textContent='Brief copied.';}catch{$('#brief-output').select();$('#brief-status').textContent='Select and copy your brief above.';}};$('#brief-status').textContent='Brief prepared. Open your email app to send it.';};}
 const directory=$('#directory-search');if(directory){directory.oninput=()=>{let n=0;document.querySelectorAll('[data-directory-item]').forEach(a=>{a.hidden=!a.textContent.toLowerCase().includes(directory.value.toLowerCase().trim());if(!a.hidden)n++;});document.querySelectorAll('.directory-group').forEach(g=>g.hidden=![...g.querySelectorAll('a')].some(a=>!a.hidden));$('#directory-status').textContent=n+' pages found';};}
 const inquiry=$('#inquiry-form');if(inquiry){inquiry.onsubmit=e=>{e.preventDefault();const d=new FormData(inquiry),kind=d.get('kind'),body=['Name: '+d.get('name'),'Reply email: '+d.get('email'),'Inquiry: '+kind,'','Project details: '+d.get('message'),'Reference: '+d.get('reference')].join('\n');const a=$('#send-inquiry');a.href='mailto:business@mrblindbandit.net?subject='+encodeURIComponent(kind+' inquiry')+'&body='+encodeURIComponent(body);a.hidden=false;$('#inquiry-status').textContent='Your inquiry is prepared. Open your email app below and send it to deliver your message.';};}
 }
 init();
})();
