(()=>{
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;};
 const link=(label,href)=>{const a=el('a',label,'text-link');a.href=href;return a;};
 async function api(path,method='GET',data){const r=await fetch('/api/community/'+path,{method,headers:method==='GET'?{}:{'content-type':'application/json'},body:data?JSON.stringify(data):undefined});let b;try{b=await r.json();}catch{throw Error('The community is temporarily unavailable. Try again shortly.');}if(!r.ok)throw Error(b.error||'Request could not be completed.');return b;}
 function stamp(time){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(time));}
 function button(label,fn,cls=''){const b=el('button',label,cls);b.type='button';b.onclick=fn;return b;}
 async function init(){
  const root=document.querySelector('[data-community]');if(!root)return;
  root.replaceChildren();const status=el('p','Loading the community…','community-status');status.setAttribute('role','status');root.append(status);
  let me;try{me=await api('me');}catch(e){status.textContent=e.message;root.append(button('Try again',init));return;}if(!root.isConnected)return;
  const auth=el('div',null,'community-auth');if(!me.signedIn){auth.append(el('p','Read the conversations, or sign in with ChatGPT to post, comment, and vote.'));const a=link('Sign in with ChatGPT','/signin-with-chatgpt?return_to='+encodeURIComponent(location.pathname+location.search));a.target='_top';auth.append(a);}else{auth.append(el('p','You’re signed in. Your chosen display name appears on public posts.'));const a=link('Sign out','/signout-with-chatgpt?return_to='+encodeURIComponent(location.pathname));a.target='_top';auth.append(a);if(me.moderator)auth.append(link('Moderation','/community/moderation/'));}auth.append(link('Community account','/community/account/'),link('My dashboard','/community/dashboard/'));if(me.moderator)auth.append(link('Owner inbox','/owner/inbox/'));const create=link('New post','/community/?compose=1#new-post');create.className='button';auth.prepend(create);root.append(auth);status.textContent='';
  if(root.dataset.community==='account'){
   if(!me.signedIn){status.textContent='Sign in above to create your community profile. Your ChatGPT credentials stay with ChatGPT.';return;}
   const f=el('form',null,'fan-composer');f.append(el('h2','Your community profile'));const label=el('label','Public display name'),input=el('input');input.required=true;input.maxLength=40;input.value=me.displayName||'';label.append(input);f.append(label);const save=el('button','Save profile','button');save.type='submit';f.append(save);f.onsubmit=async e=>{e.preventDefault();try{await api('profile','POST',{displayName:input.value});status.textContent='Your profile is saved. You can start posting and commenting.';}catch(e){status.textContent=e.message;}};root.append(f);return;
  }
  if(root.dataset.community==='dashboard'){
   if(!me.signedIn){status.textContent='Sign in above to see your posts and comments.';return;}
   try{const d=await api('dashboard');root.append(el('h2','Your discussions'));if(!d.posts.length)root.append(el('p','You haven’t started a discussion yet.'));d.posts.forEach(p=>{const item=el('article',null,'fan-post');item.append(p.hidden?el('p',p.title+' · Removed'):link(p.title,'/community/?post='+p.id),el('p',p.board+' · '+stamp(p.created_at),'small'));root.append(item);});root.append(el('h2','Your comments'));if(!d.comments.length)root.append(el('p','You haven’t commented yet.'));d.comments.forEach(c=>{const item=el('article',null,'fan-comment');item.append(link(c.title,'/community/?post='+c.post_id),el('p',c.body,'post-body'));root.append(item);});}catch(e){status.textContent=e.message;}return;
  }
  if(root.dataset.community==='moderation'){
   if(!me.moderator){status.textContent=me.signedIn?'This area is for the site owner.':'Sign in as the site owner to view reports.';return;}
   try{const r=await api('reports');if(!r.reports.length)status.textContent='No reports to review.';r.reports.forEach(p=>{const a=el('article',null,'fan-post');a.append(el('h2',p.title),el('p',p.reason),el('p',stamp(p.created_at),'small'));if(p.hidden)a.append(el('p','Post already hidden.'));else a.append(button('Hide reported post',async()=>{try{await api('posts/'+p.post_id,'DELETE',{});init();}catch(e){status.textContent=e.message;}}));root.append(a);});}catch(e){status.textContent=e.message;}return;
  }
  if(root.dataset.community==='poll'){
   const panel=el('section',null,'poll-panel');root.append(panel);async function load(){try{const p=await api('poll');panel.replaceChildren(el('h2','What would you like to talk about next?'));const total=p.counts.reduce((s,c)=>s+c.count,0);p.choices.forEach(choice=>{const count=p.counts.find(c=>c.choice===choice)?.count||0;const row=el('div',null,'poll-row');row.append(el('p',choice+(p.choice===choice?' · Your vote':'')),el('p',`${count} vote${count===1?'':'s'}`));const meter=el('meter');meter.min=0;meter.max=Math.max(total,1);meter.value=count;meter.setAttribute('aria-label',choice+' votes');row.append(meter);if(me.signedIn)row.append(button('Vote for '+choice,async()=>{try{await api('poll','POST',{choice});await load();}catch(e){status.textContent=e.message;}}));panel.append(row);});panel.append(el('p',total+' total votes. You can change your vote.','small'));}catch(e){status.textContent=e.message;}}await load();return;
  }
  const selected=new URLSearchParams(location.search).get('post');
  function ownButton(item,type,done){return button('Remove '+type,async()=>{if(!confirm('Remove this '+type+'?'))return;try{await api(type==='post'?'posts/'+item.id:'comments/'+item.id,'DELETE',{});done();}catch(e){status.textContent=e.message;}});}
  function postCard(p,detail=false){const card=el('article',null,'fan-post');const title=detail?el('h2',p.title):link(p.title,'/community/?post='+encodeURIComponent(p.id));card.append(el('p',p.board.toUpperCase()+' · '+p.displayName+' · '+stamp(p.createdAt),'eyebrow'),title,el('p',p.body,'post-body'));if(!detail)card.append(link('Read & reply'+(p.comments?' ('+p.comments+')':''),'/community/?post='+encodeURIComponent(p.id)));if(p.canDelete)card.append(ownButton(p,'post',()=>location.assign('/community/')));if(detail&&me.signedIn)card.append(button('Report post',()=>{const form=el('form',null,'report-form');const label=el('label','Reason for reporting');const input=el('textarea');input.required=true;input.maxLength=500;label.append(input);form.append(label);const send=el('button','Send report');send.type='submit';form.append(send);form.onsubmit=async e=>{e.preventDefault();try{await api('posts/'+p.id+'/report','POST',{reason:input.value});form.replaceChildren(el('p','Report sent to the site owner.'));}catch(e){status.textContent=e.message;}};card.append(form);}));return card;}
  function composer(kind,postId){const f=el('form',null,'fan-composer');f.append(el('h2',kind==='post'?'Start a conversation':'Add a comment'));function field(name,label,max,area=false){const l=el('label',label),i=el(area?'textarea':'input');i.name=name;i.required=true;i.maxLength=max;if(area)i.rows=5;l.append(i);f.append(l);return i;}field('displayName','Public display name',40).value=me.displayName||'';if(kind==='post')field('title','Discussion title',120);const body=field('body',kind==='post'?'Your post':'Your comment',kind==='post'?3000:2000,true);let board;
   if(kind==='post'){const label=el('label','Board');board=el('select');['general','music','creators',...(me.moderator?['announcements']:[])].forEach(v=>{const o=el('option',v[0].toUpperCase()+v.slice(1));o.value=v;board.append(o);});board.value=root.dataset.board||'general';label.append(board);f.append(label);}
   const note=el('p','Posts and comments are public. Keep private contact details out of your message.','small');f.append(note,link('Community guidelines','/community/guidelines/'));const send=el('button',kind==='post'?'Publish post':'Publish comment','button');send.type='submit';f.append(send);const message=el('p');message.setAttribute('role','status');f.append(message);f.onsubmit=async e=>{e.preventDefault();send.disabled=true;message.textContent='Saving…';const values=Object.fromEntries(new FormData(f));if(board)values.board=board.value;try{const r=await api(kind==='post'?'posts':'posts/'+postId+'/comments','POST',values);if(kind==='post')location.assign('/community/?post='+r.id);else{await init();}}catch(e){message.textContent=e.message;send.disabled=false;}};return f;}
  if(selected){try{const r=await api('posts/'+encodeURIComponent(selected));root.append(link('Back to discussions','/community/'),postCard(r.post,true),el('h2','Comments'));if(!r.comments.length)root.append(el('p','No comments yet. Start the conversation.'));r.comments.forEach(c=>{const a=el('article',null,'fan-comment');a.append(el('p',c.displayName+' · '+stamp(c.createdAt),'eyebrow'),el('p',c.body,'post-body'));if(c.canDelete)a.append(ownButton(c,'comment',init));root.append(a);});if(me.signedIn)root.append(composer('comment',selected));}catch(e){status.textContent=e.message;}return;}
  if(me.signedIn&&(root.dataset.board!=='announcements'||me.moderator)){const compose=composer('post');compose.id='new-post';compose.prepend(el('h2','Create a new post'));root.append(compose);if(new URLSearchParams(location.search).has('compose')){compose.scrollIntoView({block:'start'});compose.querySelector('[name=title]')?.focus();}}
  const feed=el('div',null,'fan-feed');root.append(feed);let next=null;const more=button('Load more discussions',()=>load(next));more.hidden=true;root.append(more);
  async function load(cursor){status.textContent='Loading discussions…';try{const q=new URLSearchParams();if(root.dataset.board)q.set('board',root.dataset.board);if(cursor)q.set('before',cursor);const r=await api('posts?'+q);if(!root.isConnected)return;r.posts.forEach(p=>feed.append(postCard(p)));next=r.next;more.hidden=!next;status.textContent=!feed.children.length?'No discussions here yet. Be the first to start one.':'';}catch(e){status.textContent=e.message;more.hidden=false;more.textContent='Try loading again';}}await load();
 }
 window.addEventListener('site:navigate',init);init();
})();
