(()=>{
 async function init(){
  document.querySelectorAll('[data-native-form]').forEach(form=>{form.onsubmit=async e=>{e.preventDefault();const message=form.querySelector('[role=status]'),button=form.querySelector('button[type=submit]');button.disabled=true;message.textContent='Saving your form…';try{const r=await fetch('/api/forms/'+form.dataset.nativeForm,{method:'POST',body:new FormData(form)});const result=await r.json();if(!r.ok)throw Error(result.error||'Your form could not be saved.');message.textContent=result.message+(result.reference?' Reference: '+result.reference:'');form.reset();}catch(e){message.textContent=e.message||'Unable to save. Please try again.';window.BBAccessibility?.formError(form,message.textContent);}finally{button.disabled=false;}};});
  const root=document.querySelector('[data-owner-inbox]');if(!root)return;root.replaceChildren();const message=document.createElement('p');message.setAttribute('role','status');message.textContent='Loading your inbox…';root.append(message);
  try{const r=await fetch('/api/inbox'),data=await r.json();if(!r.ok){message.textContent=data.error;const sign=document.createElement('a');sign.href='/signin-with-chatgpt?return_to=%2Fowner%2Finbox%2F';sign.target='_top';sign.className='button';sign.textContent='Sign in as site owner';root.append(sign);return;}message.textContent=data.requests.length?data.requests.length+' recent entries':'Your inbox is ready. New submissions, signups, and inquiries will appear here.';
   for(const item of data.requests){const card=document.createElement('article');card.className='inbox-entry';const heading=document.createElement('h2');heading.textContent=item.kind.toUpperCase()+' · '+(item.name||item.email);card.append(heading);const contact=document.createElement('a');contact.href='mailto:'+encodeURIComponent(item.email);contact.textContent=item.email;card.append(contact);const date=document.createElement('p');date.className='small';date.textContent=new Date(item.created_at).toLocaleString();card.append(date);const details=JSON.parse(item.details);for(const [k,v] of Object.entries(details)){const p=document.createElement('p');p.textContent=k+': '+v;card.append(p);}if(item.file_name){const a=document.createElement('a');a.href='/api/inbox/'+item.id+'/file';a.textContent='Download '+item.file_name;a.className='text-link';a.setAttribute('data-full-navigation','');card.append(a);}const remove=document.createElement('button');remove.type='button';remove.textContent='Delete entry';remove.onclick=async()=>{if(!confirm('Permanently delete this entry and its uploaded file?'))return;try{const result=await fetch('/api/inbox/'+item.id,{method:'DELETE'});if(!result.ok)throw Error('Could not delete.');card.remove();}catch(e){message.textContent=e.message;}};card.append(remove);root.append(card);}
  }catch(e){message.textContent='The inbox is temporarily unavailable. Please reload to try again.';}
 }
 addEventListener('site:navigate',init);init();
})();

;(()=>{const apply=()=>{const d=new URLSearchParams(location.search).get('department');const f=document.querySelector('form [name=category]');if(d&&f){if(f.tagName==='SELECT'&&!Array.from(f.options).some(o=>o.value===d)){const o=document.createElement('option');o.value=d;o.textContent=d;f.append(o);}f.value=d;}};apply();document.addEventListener('site:navigate',apply);})();
