(()=>{
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=x=>new Date(x).toLocaleString();
const input=(label,name,max=160)=>`<label>${label}<input name="${name}" maxlength="${max}" required></label>`;
const area=(label,name,max=6000)=>`<label>${label}<textarea name="${name}" rows="7" maxlength="${max}" required></textarea></label>`;
const select=(label,name,values)=>`<label>${label}<select name="${name}">${values.map(x=>`<option value="${x}">${x}</option>`).join('')}</select></label>`;
const form=(body,label)=>`<form class="label-form">${body}<button class="button" type="submit">${label}</button><p role="status"></p></form>`;
function handle(f,fn){f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button[type=submit]'),s=f.querySelector('[role=status]');b.disabled=true;s.textContent='Saving…';try{await fn(Object.fromEntries(new FormData(f)),s);}catch(e){s.textContent=e.message;}finally{b.disabled=false;}};}
async function announcements(panel,a,api){
 const d=await api('portal/operations/announcements'),manage=['owner','admin'].includes(a.role);
 panel.innerHTML='<h2>Label announcements</h2><p>Private updates for invited label accounts. These messages are not published to the fan community.</p><div data-compose></div><div data-announcements></div>';
 const box=panel.querySelector('[data-compose]'),list=panel.querySelector('[data-announcements]');
 function edit(r){box.innerHTML=form(input('Title','title')+area('Announcement','body')+select('Audience','audience',['all','staff','clients'])+select('Status','status',['draft','published','archived']),'Save announcement');const f=box.querySelector('form');if(r)for(const k of ['title','body','audience','status'])f.elements[k].value=r[k];handle(f,async values=>{await api('portal/operations/announcements',r?'PATCH':'POST',{...values,...(r?{id:r.id,revision:r.revision}:{})});await announcements(panel,a,api);});f.elements.title.focus();}
 if(manage){box.innerHTML='<button class="button" data-new>New announcement</button>';box.querySelector('button').onclick=()=>edit();}
 list.innerHTML=d.records.length?d.records.map(r=>`<article class="label-task"><p class="eyebrow">${esc(r.audience)} · ${esc(r.status)} · ${date(r.updatedAt)}</p><h3>${esc(r.title)}</h3><p class="preserve-lines">${esc(r.body)}</p>${manage?`<button data-edit="${r.id}">Edit announcement</button>`:''}</article>`).join(''):'<p>No announcements yet.</p>';
 list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(d.records.find(r=>r.id===b.dataset.edit)));
}
async function render(view,panel,a,api){
 if(view==='authenticator'){
 const d=await api('portal/security/authenticator');panel.innerHTML='<h2>Google Authenticator</h2><p>'+(d.enabled?'Authenticator enabled. Choose “Use Google Authenticator” when verifying your administrator session.':'Set up time-based codes using Google Authenticator or a compatible app.')+'</p><p>Verify a fresh code in <a href="/portal/security/" data-full-navigation>Account & security</a> first. Email and saved recovery codes remain available if you lose your device.</p><div data-setup></div>';
 const box=panel.querySelector('[data-setup]');if(!d.enabled){box.innerHTML='<button class="button">Begin setup</button>';box.querySelector('button').onclick=async()=>{try{const r=await api('portal/security/authenticator','POST',{action:'begin'});box.innerHTML='<h3>Enter this setup key in your authenticator app</h3><p>Choose a time-based account named Blindbandit Records. Keep this key private. Setup expires after ten minutes.</p><pre tabindex="0">'+esc(r.secret)+'</pre><button data-copy>Copy setup key</button><p><a href="'+esc(r.uri)+'">Open compatible authenticator app</a></p>'+form(input('Six-digit code from the app','code',6),'Enable authenticator');box.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(r.secret);box.querySelector('[role=status]').textContent='Setup key copied.';}catch{box.querySelector('[role=status]').textContent='Select and copy the setup key above.';}};handle(box.querySelector('form'),async v=>{await api('portal/security/authenticator','POST',{...v,action:'enable'});await render(view,panel,a,api);});}catch(e){box.textContent=e.message;}};}else{box.innerHTML=form(input('New code from your authenticator to disable it','code',6),'Disable authenticator');handle(box.querySelector('form'),async v=>{await api('portal/security/authenticator','POST',{...v,action:'disable'});location.assign('/portal/security/');});}return;
 }
 if(view==='account-sessions'){
 const d=await api('portal/account-admin/sessions');panel.innerHTML='<h2>Account sessions</h2><p>'+esc(d.scope)+'</p><p>IP addresses and browser details come from recorded sessions. They do not identify a precise physical location; VPNs and shared networks can affect them. Your separate ChatGPT owner session is managed in ChatGPT.</p><p data-session-status role="status"></p>'+d.sessions.map(r=>'<article class="label-task"><h3>'+esc(r.name)+'</h3><p>'+esc(r.email)+'</p><p>IP address: '+esc(r.ip_address||'Not recorded')+'</p><p>Browser: '+esc(r.user_agent||'Not recorded')+'</p><p>Signed in: '+date(r.created_at)+' · Expires: '+date(r.expires_at)+'</p>'+(r.current?'<p>Current session</p>':'<button data-end="'+esc(r.id)+'">Sign out this session</button>')+'</article>').join('');panel.querySelectorAll('[data-end]').forEach(b=>b.onclick=async()=>{if(!confirm('Sign out this account session?'))return;try{await api('portal/account-admin/sessions','POST',{id:b.dataset.end});await render(view,panel,a,api);}catch(e){panel.querySelector('[role=status]').textContent=e.message;}});return;
 }
 if(view==='community-accounts'){
 const d=await api('portal/account-admin/community-accounts');
 const active=d.accounts.filter(r=>r.status!=='suspended').length,suspended=d.accounts.length-active;
 panel.innerHTML='<section class="workspace-hero"><p class="eyebrow">LABEL OS · SOCIAL BRIDGE</p><h2>Community accounts</h2><p>Invite fans with the email on their production Clerk account. Profiles claim at the next Blindbandit Mobile or community sign-in. This does not create a private label portal account.</p><div class="workspace-actions"><a class="button" href="/mobile/admin/" data-full-navigation>Open Social Admin Control Center</a><a href="/mobile/" data-full-navigation>Open Blindbandit Mobile</a><a href="/community/" data-full-navigation>Fan community</a><a href="/portal/moderation-casework/" data-full-navigation>Moderation casework</a></div></section><div class="label-stats"><article><span>Invitations</span><strong>'+d.accounts.length+'</strong></article><article><span>Active</span><strong>'+active+'</strong></article><article><span>Suspended</span><strong>'+suspended+'</strong></article></div><details class="label-compose" '+(d.accounts.length?'':'open')+'><summary>Create a community invitation</summary>'+form(input('Public display name','name',40)+input('Clerk account email','email',254),'Create profile invitation & send email')+'<p class="small">Use the verified production Clerk email the fan will sign in with. Invitation emails are operational notices, not marketing.</p></details><div class="workspace-toolbar"><label>Search invitations<input type="search" data-ca-search placeholder="Name or email"></label><label>Status<select data-ca-status><option value="">All</option><option>active</option><option>suspended</option><option>invited</option></select></label></div><p role="status" data-ca-status-msg></p><div data-ca-list></div>';
 const draw=()=>{const q=(panel.querySelector('[data-ca-search]').value||'').toLowerCase(),st=panel.querySelector('[data-ca-status]').value;const rows=d.accounts.filter(r=>((!st||r.status===st)&&(!q||(r.name+' '+r.email).toLowerCase().includes(q))));panel.querySelector('[data-ca-list]').innerHTML=rows.length?rows.map(r=>'<article class="label-task"><div class="label-section-bar"><span class="label-tag status-'+(r.status==='suspended'?'bad':r.status==='active'?'ok':'warn')+'">'+esc(r.status)+'</span></div><h3>'+esc(r.name)+'</h3><p>'+esc(r.email)+'</p><div class="workspace-actions"><button data-account="'+esc(r.key)+'" data-state="'+(r.status==='suspended'?'active':'suspended')+'">'+(r.status==='suspended'?'Restore community access':'Suspend community access')+'</button><a href="/mobile/admin/" data-full-navigation>Moderate in Social Admin</a></div></article>').join(''):'<div class="label-empty portal-empty-rich"><img src="/assets/empty-state-castle-aurora-v2.jpg" alt="" width="240" height="140" decoding="async"><h3>No matching community invitations</h3><p>Create an invitation above, or open Social Admin to moderate Blindbandit Mobile members who already signed in with Clerk.</p></div>';panel.querySelectorAll('[data-account]').forEach(b=>b.onclick=async()=>{try{await api('portal/account-admin/community-accounts','PATCH',{key:b.dataset.account,status:b.dataset.state});await render(view,panel,a,api);}catch(e){panel.querySelector('[data-ca-status-msg]').textContent=e.message;}});};
 handle(panel.querySelector('form'),async(v,s)=>{const r=await api('portal/account-admin/community-accounts','POST',v);s.textContent=r.delivery==='accepted'?'Invitation saved and accepted by the email provider. Refresh to see the account.':'Invitation saved, but email delivery failed. The fan can still open Mobile/community and sign in with the invited email.';});
 panel.querySelector('[data-ca-search]').oninput=draw;panel.querySelector('[data-ca-status]').onchange=draw;draw();return;
 }
 if(view==='search'){
 panel.innerHTML='<h2>Search your portal</h2><p>Find pages, tasks, workspace records and articles available to your account.</p>'+form(input('Search words','q',150),'Search')+'<section data-results aria-live="polite"></section>';handle(panel.querySelector('form'),async v=>{const d=await api('portal/tools/search?q='+encodeURIComponent(v.q));panel.querySelector('[data-results]').innerHTML='<p>'+esc(d.message)+'</p>'+d.results.map(r=>'<article class="label-task"><p>'+esc(r.kind)+(r.status?' · '+esc(r.status):'')+'</p><h3><a href="'+esc(r.path)+'" data-full-navigation>'+esc(r.title)+'</a></h3></article>').join('');panel.querySelector('[role=status]').textContent=d.results.length+' results.';});return;
 }
 if(view==='shortcuts'){
 const d=await api('portal/tools/shortcuts');panel.innerHTML='<h2>My shortcuts</h2><p>Save up to 20 portal pages. Your choices follow your account across devices.</p><nav aria-label="Saved shortcuts">'+(d.paths.map(path=>'<p><a href="'+esc(path)+'" data-full-navigation>'+esc(d.available.find(x=>x.path===path).title)+'</a></p>').join('')||'<p>No shortcuts saved yet.</p>')+'</nav>'+form('<fieldset><legend>Choose your pages</legend>'+d.available.map(p=>'<label><input type="checkbox" name="page" value="'+esc(p.path)+'" '+(d.paths.includes(p.path)?'checked':'')+'> '+esc(p.title)+'</label>').join('')+'</fieldset>','Save shortcuts');handle(panel.querySelector('form'),async()=>{const paths=[...panel.querySelectorAll('[name=page]:checked')].map(x=>x.value);await api('portal/tools/shortcuts','POST',{paths,revision:d.revision});await render(view,panel,a,api);});return;
 }
 if(view==='guide'){
 const admin=['owner','admin'].includes(a.role);const entries=[['password security reset','Account & security','security/','Change your password, review sessions and generate recovery codes.'],['earnings royalties statement','Earnings','earnings/','Review recorded earnings. Amounts are entered by label staff.'],['message contact conversation','Messages','messages/','Open your private client conversations.'],['task project deadline','Tasks','tasks/','Review assigned tasks and update progress.'],['announcement internal private','Label announcements','announcements/','Read updates shared with your account.'],...(admin?[['publish post public announcement forum','Public announcements','community-publishing/?board=announcements','Choose Announcements and publish as Blindbandit Records. This is public.'],['article news slug title','Publishing studio','publishing/','Write the body, suggest missing details, preview, then save or publish.'],['invite client team account','Team & access','team/','Invite accounts and manage their roles.'],['inbox submission reply','Submission inbox','inbox/','Review website submissions and reply from the private inbox.']]:[]),...(window.LabelWorkspaceModules||[]).filter(m=>m.roles.includes(a.role)).map(m=>[m.title+' '+m.description,m.title,m.slug+'/',m.description])];
 panel.innerHTML='<h2>What would you like to do?</h2><p>This guide matches words to portal tools. It is not AI and does not read your private messages or change records.</p>'+form(input('Describe your task','question',200),'Find a tool')+'<section data-answers aria-live="polite"></section>';
 handle(panel.querySelector('form'),async v=>{const terms=v.question.toLowerCase().match(/[a-z]{3,}/g)||[],ranked=entries.map(e=>({e,score:terms.filter(t=>e[0].toLowerCase().includes(t)).length})).filter(x=>x.score).sort((x,y)=>y.score-x.score).slice(0,6);panel.querySelector('[data-answers]').innerHTML=ranked.length?ranked.map(({e})=>'<article class="label-task"><h3><a href="/portal/'+e[2]+'" data-full-navigation>'+esc(e[1])+'</a></h3><p>'+esc(e[3])+'</p></article>').join(''):'<p>No matching tool found. Try “post announcement”, “invite client”, “earnings” or “password”.</p>';panel.querySelector('[role=status]').textContent='Guide results ready.';});return;
 }
 if(view==='announcements')return announcements(panel,a,api);
 if(view==='community-publishing'){
  const d=await api('portal/operations/community');panel.innerHTML='<h2>Publish a community post</h2><p>Your post appears publicly as Blindbandit Records. Use Label announcements for private team or client updates.</p>'+form(input('Post title','title',120)+area('Post','body',3000)+select('Board','board',['general','music','creators','announcements']),'Publish public post')+'<h2>Your dashboard posts</h2><div data-posts></div>';
  if(new URLSearchParams(location.search).get('board')==='announcements')panel.querySelector('[name=board]').value='announcements';
  handle(panel.querySelector('form'),async(v,s)=>{const r=await api('portal/operations/community','POST',v);panel.querySelector('form').reset();s.innerHTML=`Published. <a href="/community/?post=${r.id}" data-full-navigation>Open your post</a>`;});
  panel.querySelector('[data-posts]').innerHTML=d.posts.length?d.posts.map(r=>`<article class="label-task"><h3>${esc(r.title)}</h3><p>${esc(r.board)} · ${date(r.created_at)}${r.hidden?' · Removed':''}</p>${r.hidden?'':`<a href="/community/?post=${r.id}" data-full-navigation>View public post</a> <button data-remove="${r.id}">Remove post</button>`}</article>`).join(''):'<p>No posts published from this label account yet.</p>';
  panel.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this public post?'))return;b.disabled=true;try{await api('portal/operations/community','DELETE',{id:b.dataset.remove});await render(view,panel,a,api);}catch(e){b.disabled=false;panel.querySelector('[role=status]').textContent=e.message;}});return;
 }
 if(view==='readiness'){
  const d=await api('portal/operations/readiness');panel.innerHTML='<h2>Rights & delivery readiness</h2><p>Live counts from your private records. Approval statuses reflect your team’s review, not a provider’s eligibility decision.</p><div class="label-stats">'+d.modules.map(m=>`<article><h3><a data-full-navigation href="/portal/${m.slug}/">${esc(m.title)}</a></h3><strong>${m.statuses.reduce((n,s)=>n+s.count,0)}</strong><span>Active records · ${m.overdue} overdue</span>${m.statuses.map(s=>`<p>${esc(s.status)}: ${s.count}</p>`).join('')||'<p>No records yet</p>'}</article>`).join('')+'</div>';return;
 }
 if(view==='lockdown'){
  const d=await api('portal/operations/lockdown');panel.innerHTML=`<h2>Emergency portal lockdown</h2><p><strong>${d.locked?'Portal locked':'Portal open'}</strong></p><p>Locking blocks non-owner label access and signs out their current sessions. Your owner account remains available to unlock the portal. Public pages and community access stay available.</p><p>Verify a fresh code in <a href="/portal/security/" data-full-navigation>Account & security</a> before changing this setting.</p>`+form(input('Type '+(d.locked?'UNLOCK PORTAL':'LOCK PORTAL'),'confirmation'),'Confirm '+(d.locked?'unlock':'lockdown'));handle(panel.querySelector('form'),async v=>{await api('portal/operations/lockdown','POST',{enabled:!d.locked,confirmation:v.confirmation});await render(view,panel,a,api);});return;
 }
 if(view==='content-backups'){
  const d=await api('portal/operations/backups');panel.innerHTML='<h2>Private article snapshots</h2><p>Save up to 50 Publishing studio articles per snapshot, with 20 retained snapshots and a 4 MB limit each. This does not back up accounts, contracts, uploaded media, community posts or the entire database. Snapshots are created on demand.</p><p>Restore recovers a separate draft and leaves the current article intact. Review the draft before publishing. Creation, restoration and deletion require fresh verification in <a href="/portal/security/" data-full-navigation>Account & security</a>.</p>'+form('','Create article snapshot')+'<div data-backups></div><section data-restore></section>';
  handle(panel.querySelector('form'),async()=>{await api('portal/operations/backups','POST',{action:'create'});await render(view,panel,a,api);});
  panel.querySelector('[data-backups]').innerHTML=d.records.length?d.records.map(r=>`<article class="label-task"><h3>${date(r.createdAt)}</h3><p>${r.count} articles · ${esc(r.id)}</p><a href="/api/portal/operations/backups?id=${r.id}" download>Download private JSON</a> <button data-browse="${r.id}">Choose article to restore</button> <button data-delete="${r.id}">Delete snapshot</button></article>`).join(''):'<p>No snapshots saved yet.</p>';
  panel.querySelectorAll('[data-browse]').forEach(b=>b.onclick=async()=>{const box=panel.querySelector('[data-restore]');try{const snapshot=await api('portal/operations/backups?id='+b.dataset.browse);box.innerHTML='<h3>Restore one article as a new draft</h3>'+form('<label>Article<select name="articleId">'+snapshot.articles.map(r=>`<option value="${esc(r.id)}">${esc(r.title)}</option>`).join('')+'</select></label>'+input('Type RESTORE AS DRAFT','confirmation'),'Restore draft');handle(box.querySelector('form'),async(v,s)=>{const r=await api('portal/operations/backups','POST',{...v,id:b.dataset.browse,action:'restore'});s.textContent=r.message;});box.scrollIntoView({block:'start'});}catch(e){box.textContent=e.message;}});
  panel.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const phrase=prompt('Type DELETE SNAPSHOT to permanently remove this snapshot.');if(!phrase)return;try{await api('portal/operations/backups','DELETE',{id:b.dataset.delete,confirmation:phrase});await render(view,panel,a,api);}catch(e){panel.querySelector('[role=status]').textContent=e.message;}});return;
 }
}
async function overview(panel,a,api){const d=await api('portal/operations/announcements'),records=d.records.filter(r=>r.status==='published'&&(r.audience==='all'||r.audience===(a.role==='client'?'clients':'staff'))).slice(0,3);const box=document.createElement('section');box.className='label-announcement-preview';box.innerHTML='<h2>Label announcements</h2><a href="/portal/announcements/" data-full-navigation>Open announcements</a>'+(['owner','admin'].includes(a.role)?' · <a href="/portal/community-publishing/" data-full-navigation>Publish a community post</a> · <a href="/portal/community-publishing/?board=announcements" data-full-navigation>Post a public announcement</a> · <a href="/mobile/admin/" data-full-navigation>Social Admin</a> · <a href="/portal/notifications/" data-full-navigation>Notifications</a>':'')+(records.map(r=>`<article class="label-task"><h3>${esc(r.title)}</h3><p class="preserve-lines">${esc(r.body.slice(0,350))}</p></article>`).join('')||'<p>No current announcements.</p>');panel.prepend(box);}
window.LabelOperations={render,overview};
})();
