(()=>{
 const money=(amount,currency)=>new Intl.NumberFormat(undefined,{style:'currency',currency:currency||'USD'}).format((amount||0)/100);
 async function json(url,options){const r=await fetch(url,{credentials:'same-origin',...options});let d;try{d=await r.json();}catch{throw Error('The payment service is temporarily unavailable.');}if(!r.ok)throw Error(d.error||'Unable to complete this request.');return d;}
 function init(){
  const form=document.querySelector('[data-stripe-checkout]');if(form&&!form.dataset.ready){form.dataset.ready='true';let attempt=crypto.randomUUID();form.querySelectorAll('[data-support-amount]').forEach(b=>b.onclick=()=>{form.elements.amount.value=b.dataset.supportAmount;attempt=crypto.randomUUID();form.elements.amount.focus();});form.elements.amount.addEventListener('input',()=>attempt=crypto.randomUUID());form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]'),status=form.querySelector('[role=status]');button.disabled=true;status.textContent='Opening secure checkout…';try{const d=await json('/api/payments/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount:form.elements.amount.value,agree:form.elements.agree.checked,attempt})});const url=new URL(d.url);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com')throw Error('Checkout returned an unexpected destination.');location.assign(url.href);}catch(err){status.textContent=err.message;button.disabled=false;}};}
  const receipt=document.querySelector('[data-stripe-receipt]');if(receipt&&!receipt.dataset.ready){receipt.dataset.ready='true';const status=receipt.querySelector('[role=status]'),button=receipt.querySelector('button'),summary=receipt.querySelector('dl');const check=async()=>{button.disabled=true;status.textContent='Checking Stripe…';try{const d=await json('/api/payments/receipt');status.textContent=d.status==='paid'?'Payment confirmed. Thank you for supporting Mr. Blindbandit.':d.checkoutStatus==='expired'?'This checkout expired. No paid result is recorded for this checkout.':d.checkoutStatus==='complete'?'Your payment is processing. Please check again before making another payment.':'This checkout has not recorded a completed payment.';summary.replaceChildren();for(const [label,value] of [['Amount',money(d.amount,d.currency)],['Status',d.status],['Reference',d.reference]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;dd.style.overflowWrap='anywhere';summary.append(dt,dd);}}catch(e){status.textContent=e.message;}finally{button.disabled=false;}};button.onclick=check;check();}
 }
 window.LabelPayments={async render(panel,actor,api){
  panel.innerHTML='<h2>Stripe payments</h2><p role="status">Connecting to Stripe…</p><div data-stripe-data></div>';
  const status=panel.querySelector('[role=status]'),box=panel.querySelector('[data-stripe-data]');let cursor=null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function load(after){try{const d=await api('portal/payments'+(after?'?after='+encodeURIComponent(after):''));cursor=d.next;status.textContent='Stripe connected. '+(d.live?'Live environment.':'Test environment.')+' Payments '+(d.chargesEnabled?'enabled.':'not enabled.')+' Payouts '+(d.payoutsEnabled?'enabled.':'not enabled.');box.innerHTML='<p>Balances below cover your entire Stripe account; payment rows show only this website’s support checkouts from the current batch of 50 Stripe sessions. They are not client royalty statements.</p><h3>Available balance</h3><p>'+esc(d.available.map(x=>money(x.amount,x.currency)).join(' · ')||'None reported')+'</p><h3>Pending balance</h3><p>'+esc(d.pending.map(x=>money(x.amount,x.currency)).join(' · ')||'None reported')+'</p><h3>Support checkout activity</h3><div class="label-table-wrap"><table><caption>Website support checkouts — current batch</caption><thead><tr><th scope="col">Date</th><th scope="col">Amount</th><th scope="col">Payment status</th><th scope="col">Checkout</th><th scope="col">Reference</th></tr></thead><tbody>'+d.payments.map(p=>'<tr><td>'+esc(new Date(p.created*1000).toLocaleString())+'</td><td>'+esc(money(p.amount,p.currency))+'</td><td>'+esc(p.status)+'</td><td>'+esc(p.checkoutStatus)+'</td><td style="overflow-wrap:anywhere">'+esc(p.id)+'</td></tr>').join('')+'</tbody></table></div>'+(!d.payments.length?'<p>No website support checkouts in this batch.</p>':'')+'<button type="button" data-refresh>Refresh latest</button> <button type="button" data-next '+(!cursor?'disabled':'')+'>Older activity</button> <button type="button" data-export>Download this batch as CSV</button><p><a href="https://dashboard.stripe.com/payments" target="_blank" rel="noopener noreferrer">Manage payments and refunds in Stripe</a> · <a href="https://dashboard.stripe.com/balance/overview" target="_blank" rel="noopener noreferrer">Stripe balance and payouts</a></p><p><a href="/support/card/" data-full-navigation>Open public support checkout</a> · <a href="/payments/help/" data-full-navigation>Payment help</a></p>';
   box.querySelector('[data-refresh]').onclick=()=>load(null);box.querySelector('[data-next]').onclick=()=>load(cursor);box.querySelector('[data-export]').onclick=()=>{const rows=[['Date','Amount minor units','Currency','Payment status','Checkout','Reference'],...d.payments.map(p=>[new Date(p.created*1000).toISOString(),p.amount,p.currency,p.status,p.checkoutStatus,p.id])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='blindbandit-support-payments.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  }catch(e){status.textContent=e.message;}}await load(null);
 }};
 init();document.addEventListener('site:navigate',init);
})();
