(()=>{
const form=document.querySelector('[data-tool]');if(!form)return;
const out=form.querySelector('.tool-result'),money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(n),num=n=>Number(form.elements[n]?.value||0),clean=s=>String(s||'').trim(),download=(name,text)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.download=name;document.body.append(a);a.click();URL.revokeObjectURL(a.href);a.remove();},show=text=>{out.textContent=text;};let generated='';
if(form.dataset.tool==='budget')form.onsubmit=e=>{e.preventDefault();const total=['production','artwork','marketing','distribution','reserve'].reduce((n,k)=>n+num(k),0),rate=num('rate');show(`Estimated budget: ${money(total)}. At the planning rate entered, recovering that amount would require approximately ${rate>0?Math.ceil(total/rate).toLocaleString():'—'} streams before taxes, deductions, splits, or fees.`);};
if(form.dataset.tool==='split'){const run=()=>{const rows=[1,2,3,4].map(i=>[clean(form.elements['name'+i].value),num('share'+i)]).filter(x=>x[0]||x[1]),total=rows.reduce((n,x)=>n+x[1],0);generated=['Royalty split planning summary','',...rows.map(x=>`${x[0]||'Unnamed participant'}: ${x[1].toFixed(2)}%`),'',`Total: ${total.toFixed(2)}%`,Math.abs(total-100)<.001?'Status: Shares total 100%.':'Status: Adjust shares so the total equals 100%.','',`Prepared ${new Date().toLocaleString()}`].join('\n');show(generated);return generated;};form.onsubmit=e=>{e.preventDefault();run();};form.querySelector('[data-download]').onclick=()=>download('royalty-split-summary.txt',run());}
if(form.dataset.tool==='metadata'){const key='blindbandit-metadata-checklist-v1',boxes=[...form.querySelectorAll('input[type=checkbox]')],report=()=>{const done=boxes.filter(b=>b.checked).length;show(`${done} of ${boxes.length} release checks complete.`);return ['Release metadata checklist','',...boxes.map(b=>`${b.checked?'[complete]':'[ ]'} ${b.parentElement.textContent.trim()}`),'',`Prepared ${new Date().toLocaleString()}`].join('\n');};try{const saved=JSON.parse(localStorage.getItem(key)||'{}');boxes.forEach(b=>b.checked=Boolean(saved[b.name]));}catch{}report();form.onsubmit=e=>{e.preventDefault();localStorage.setItem(key,JSON.stringify(Object.fromEntries(boxes.map(b=>[b.name,b.checked]))));report();};form.onreset=()=>{localStorage.removeItem(key);setTimeout(report);};form.querySelector('[data-download]').onclick=()=>download('release-metadata-checklist.txt',report());}
const enableDocument=()=>{for(const b of form.querySelectorAll('[data-copy],[data-download]'))b.disabled=false;show(generated);};
if(form.dataset.tool==='brief')form.onsubmit=e=>{e.preventDefault();const f=new FormData(form);generated=[`COLLABORATION BRIEF — ${clean(f.get('project'))}`,`Prepared by: ${clean(f.get('artist'))}`,`Requested collaborator: ${clean(f.get('collaborator'))||'To be confirmed'}`,`Requested role: ${clean(f.get('role'))||'To be confirmed'}`,`Target date: ${clean(f.get('date'))||'To be confirmed'}`,`Budget or terms: ${clean(f.get('terms'))||'To be discussed'}`,'','CREATIVE DIRECTION',clean(f.get('direction')),'','DELIVERABLES AND REFERENCES',clean(f.get('deliverables'))||'To be discussed','','This brief is a planning document, not a contract.'].join('\n');enableDocument();};
if(form.dataset.tool==='press')form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),topics=f.getAll('topic');generated=[`INTERVIEW REQUEST BRIEF — ${clean(f.get('outlet'))}`,`Contact: ${clean(f.get('contact'))}`,`Format: ${clean(f.get('format'))}`,`Requested date: ${clean(f.get('date'))||'Flexible'}`,`Estimated duration: ${clean(f.get('duration'))||'To be confirmed'}`,`Planned publication: ${clean(f.get('publication'))||'To be confirmed'}`,'','EDITORIAL ANGLE',clean(f.get('angle')),'','PROPOSED TOPICS',topics.length?topics.map(x=>`- ${x}`).join('\n'):'- To be discussed','','Please confirm recording, quotation, editing, accessibility, and publication arrangements before the interview.'].join('\n');enableDocument();};
const copy=form.querySelector('[data-copy]');if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(generated);copy.textContent='Copied';}catch{show(generated+'\n\nCopy is unavailable in this browser. Select the text above instead.');}};const dl=form.querySelector('[data-download]');if(dl&&['brief','press'].includes(form.dataset.tool))dl.onclick=()=>download(form.dataset.tool==='press'?'interview-brief.txt':'collaboration-brief.txt',generated);
})();
