'use strict';
const $=id=>document.getElementById(id);
let diagnostics={};
function status(message,error=false){$('status').setAttribute('role',error?'alert':'status');$('status').textContent=message;}
async function api(path,method='GET',data){const r=await fetch(path,{method,credentials:'same-origin',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});let body;try{body=await r.json();}catch{throw Error('Unexpected response. Refresh the page and try again.');}if(!r.ok||!body.success)throw Error((body.error?.message||'Request failed.')+(body.error?.request_id?' Request ID: '+body.error.request_id:''));return body.data;}
function action(id,fn){$(id).addEventListener('click',async event=>{event.preventDefault();const button=event.currentTarget;button.disabled=true;try{await fn();}catch(e){status(e.message,true);}finally{button.disabled=false;}});}
function form(id,fn){$(id).addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{await fn();}catch(e){status(e.message,true);}finally{button.disabled=false;}});}
function show(id,value){$(id).textContent=JSON.stringify(value,null,2);}
function field(parent,label,type='text'){const id='field-'+crypto.randomUUID(),l=document.createElement('label'),i=document.createElement('input');l.htmlFor=id;l.textContent=label;i.id=id;i.type=type;i.autocomplete=type==='password'?'new-password':'off';parent.append(l,i);return i;}
function button(parent,label,fn){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',async()=>{b.disabled=true;try{await fn();}catch(e){status(e.message,true);}finally{b.disabled=false;}});parent.append(b);return b;}
async function loadVault(){const list=await api('/v1/integrations'),root=$('integrations');root.replaceChildren();for(const provider of list){const d=document.createElement('details'),s=document.createElement('summary');s.textContent=provider.name;d.append(s);const l=document.createElement('label'),select=document.createElement('select');select.id='env-'+provider.id;l.htmlFor=select.id;l.textContent=provider.name+' environment';for(const environment of ['production','staging','development']){const o=document.createElement('option');o.value=environment;o.textContent=environment;select.append(o);}d.append(l,select);const info=document.createElement('p');d.append(info);const pub={},sec={};for(const name of provider.public_fields)pub[name]=field(d,name.replaceAll('_',' '));for(const name of provider.secret_fields)sec[name]=field(d,name.replaceAll('_',' '),'password');function update(){const c=provider.configurations.find(v=>v.environment===select.value);info.textContent='Status: '+c.status.replaceAll('_',' ')+'. Saved secrets: '+c.secrets.replaceAll('_',' ');for(const key in pub)pub[key].value=c.public_config[key]||'';for(const key in sec)sec[key].value='';}select.addEventListener('change',update);update();button(d,'Save '+provider.name,async()=>{const public_config={},secret_config={};for(const key in pub)if(pub[key].value)public_config[key]=pub[key].value;for(const key in sec)if(sec[key].value)secret_config[key]=sec[key].value;try{await api('/v1/integrations/'+provider.id,'PUT',{environment:select.value,public_config,secret_config});info.textContent='Saved. Connection not yet verified.';status(provider.name+' saved.');}finally{for(const key in sec)sec[key].value='';}});button(d,'Test '+provider.name+' connection',async()=>{const result=await api('/v1/integrations/'+provider.id+'/test','POST',{environment:select.value});info.textContent=result.message;status(result.message,result.status==='error');});button(d,'Disable '+provider.name,async()=>{await api('/v1/integrations/'+provider.id+'/disable','POST',{environment:select.value});info.textContent='Disabled';status(provider.name+' disabled for the new platform.');});const confirmation=field(d,'Type DELETE CREDENTIALS to remove saved '+provider.name+' credentials');button(d,'Delete '+provider.name+' credentials',async()=>{await api('/v1/integrations/'+provider.id,'DELETE',{environment:select.value,confirmation:confirmation.value});confirmation.value='';info.textContent='Credentials deleted; integration disabled.';status(provider.name+' credentials deleted.');});root.append(d);}}
async function load(){diagnostics=await api('/v1/diagnostics');show('overview',{api:diagnostics.api_version,database:diagnostics.database,vault:diagnostics.vault_configured?'ready':'server encryption key required',owner_mobile_enabled:diagnostics.owner_mobile_enabled,server_media_jobs:diagnostics.server_media_jobs,web_push:diagnostics.web_push});const config=await api('/v1/app/config');$('maintenance').checked=config.maintenance;$('announcement').value=config.announcement;$('ios-version').value=config.ios_version;$('android-version').value=config.android_version;$('minimum-ios').value=config.minimum_ios_version;$('minimum-android').value=config.minimum_android_version;$('features').replaceChildren();for(const key of ['native_notifications','native_profile','native_label']){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.id=key;input.checked=!!config.features[key];label.append(input,document.createTextNode(' Enable '+key.replaceAll('_',' ')));$('features').append(label);}const sessions=await api('/v1/owner/sessions');$('owner-sessions').replaceChildren();for(const session of sessions.items){const box=document.createElement('div'),text=document.createElement('p');text.textContent=session.device_name+' · '+session.platform+' · '+(session.revoked_at?'Revoked':'Last used '+new Date(session.last_used_at).toLocaleString());box.append(text);if(!session.revoked_at)button(box,'Revoke '+session.device_name,async()=>{await api('/v1/owner/sessions/'+session.id,'DELETE');status('Device revoked.');await load();});$('owner-sessions').append(box);}if(!sessions.items.length)$('owner-sessions').textContent='No mobile owner sessions.';const devices=await api('/v1/push/devices');$('push-device').replaceChildren();for(const device of devices.items.filter(d=>d.enabled)){const o=document.createElement('option');o.value=device.id;o.textContent=device.platform+' · '+device.installation_id;$('push-device').append(o);}await loadVault();status('Platform status updated.');}
action('refresh',load);
action('copy-diagnostics',async()=>{await navigator.clipboard.writeText(JSON.stringify({api_version:diagnostics.api_version,database:diagnostics.database,vault_configured:diagnostics.vault_configured,owner_mobile_enabled:diagnostics.owner_mobile_enabled,server_media_jobs:diagnostics.server_media_jobs,web_push:diagnostics.web_push},null,2));status('Safe diagnostics copied.');});
action('generate-master',async()=>{$('master-secret').value=Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');status('Credential generated. Copy it to your password manager before saving.');});
action('copy-master',async()=>{if(!$('master-secret').value)throw Error('Generate or enter a credential first.');await navigator.clipboard.writeText($('master-secret').value);status('Credential copied. Save it in your password manager.');});
form('owner-form',async()=>{try{await api('/v1/owner/configure','POST',{master_secret:$('master-secret').value,enabled:$('owner-enabled').checked,confirmation:$('owner-confirmation').value});status('Owner credential saved. Previous owner devices revoked.');}finally{$('master-secret').value='';$('owner-confirmation').value='';}});
action('kill-owner',async()=>{await api('/v1/owner/disable','POST',{confirmation:$('kill-confirmation').value});$('kill-confirmation').value='';status('Mobile owner access disabled and owner devices revoked.');});
action('revoke-owner',async()=>{await api('/v1/owner/sessions/revoke-all','POST',{confirmation:$('revoke-confirmation').value});$('revoke-confirmation').value='';status('All owner devices revoked.');});
form('config-form',async()=>{const features={};for(const name of ['native_notifications','native_profile','native_label'])features[name]=$(name).checked;await api('/v1/admin/app-config','PUT',{maintenance:$('maintenance').checked,announcement:$('announcement').value,ios_version:$('ios-version').value,android_version:$('android-version').value,minimum_ios_version:$('minimum-ios').value,minimum_android_version:$('minimum-android').value,features});status('App configuration saved.');});
form('push-form',async()=>{if(!$('push-device').value)throw Error('Register a device from your app first.');const result=await api('/v1/push/test','POST',{device_id:$('push-device').value,environment:$('push-environment').value});show('deliveries',result);status('Push result: '+result.status+'. Device receipt is not confirmed.');});
form('notification-form',async()=>{await api('/v1/admin/notifications','POST',{user_id:$('notification-user').value,title:$('notification-title').value,body:$('notification-body').value,category:'announcement',deep_link:$('notification-link').value});status('In-app notification created.');});
action('load-deliveries',async()=>show('deliveries',await api('/v1/push/deliveries')));
action('load-audit',async()=>show('audit',await api('/v1/admin/audit')));
load().catch(e=>status(e.message,true));
